#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &

bspc monitor -d dev browser web tools chat media 7 8 9 10

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1' follow=on
bspc rule -a firefox-developer-edition desktop='^3' follow=on
bspc rule -a brave-bin desktop='^2' follow=on
bspc rule -a ticktick desktop='^4' follow=off
bspc rule -a discord desktop='^5' follow=on
bspc rule -a discord-ptb desktop='^5' follow=on
bspc rule -a telegram-desktop desktop='^5' follow=on
bspc rule -a authy state=floating
